- name: create a disk
  gcp_compute_disk:
      name: "{{hostname}}"
      size_gb: "{{bootdisk}}"
      source_image: "{{source_image}}"
      zone: "{{ zone }}"
      project: "{{ gcp_project_id }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes:
        - https://www.googleapis.com/auth/compute
      state: present
  delegate_to: localhost
  register: disk

- name: create a address
  gcp_compute_address:
      name: "{{hostname}}"
      region: "{{ region }}"
      project: "{{ gcp_project_id }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes:
        - https://www.googleapis.com/auth/compute
      state: present
  delegate_to: localhost
  register: address

- name: create a instance
  gcp_compute_instance:
      state: present
      name: "{{hostname}}"
      machine_type: "{{machine_type}}"
      metadata:
        istest: true
      disks:
        - auto_delete: true
          boot: true
          source: "{{ disk }}"
      network_interfaces:
        - network: 
            name: "{{ gcp_network }}"
          access_configs:
            - name: 'External NAT'
              nat_ip: "{{ address }}"
              type: 'ONE_TO_ONE_NAT'
      zone: "{{ zone }}"
      project: "{{ gcp_project_id }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes:
        - https://www.googleapis.com/auth/compute
  delegate_to: localhost
  register: instance

#- name: Wait for SSH to come up
#  wait_for: host={{ instance.network_interfaces.network_ip }} port=22 delay=10 timeout=60
