- name: delete a instance
  gcp_compute_instance:
      state: absent
      name: "{{hostname}}"
      machine_type: n1-standard-1
      metadata:
        istest: true
      zone: "{{ zone }}"
      project: "{{ gcp_project_id }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes:
        - https://www.googleapis.com/auth/compute
  delegate_to: localhost


- name: delete a disk
  gcp_compute_disk:
      name: '{{hostname}}'
      size_gb: 50
      source_image: "{{source_image}}"
      zone: "{{ zone }}"
      project: "{{ gcp_project_id }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes:
        - https://www.googleapis.com/auth/compute
      state: absent
  delegate_to: localhost
  register: disk

- name: delete a address
  gcp_compute_address:
      name: '{{hostname}}'
      region: "{{ region }}"
      project: "{{ gcp_project_id }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes:
        - https://www.googleapis.com/auth/compute
      state: absent
  delegate_to: localhost
