---

- hosts:                nodes:lb
  gather_facts:         false
  serial:               "100%"

  pre_tasks:

  - include_vars:
      file: ../vars/gcp_vars.yml

  roles:
   - gcp_create_instance
   - gcp_add_disk
