---

- hosts:                nodes:lb
  gather_facts:         false
  serial:               "100%"

  pre_tasks:

  - include_vars:
      file: ../vars/gcp_vars.yml

  roles:
   - gcp_delete_instance
   - gcp_delete_disk

- host: localhost
  tasks:
  
  - name: clean up known_hosts
    file: 
      path: "~/.ssh/known_hosts"
      state: absent
