- name: delete a disk
  gcp_compute_disk:
      name: '{{hostname}}{{index}}'
      zone: "{{ zone }}"
      project: "{{ gcp_project_id }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: absent
  delegate_to: localhost
  with_items:
    - "{{disks}}"
  loop_control:
    index_var: index
